on:
  push:
    branches:
      - 'main'
jobs:
  notify:
    name: Notify new EUKEV
    runs-on: ubuntu-latest
    steps:
      - uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: "EU KEV - new submission"
          TEXT: "New EU KEV commited"
          MATTERMOST_USERNAME: ${{ github.triggering_actor }}
