on:
  push:
    branches:
      - 'main'
jobs:
  notify:
    name: Notify new EUKEV
    runs-on: ubuntu-latest
    steps:
      - uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "New EU KEV submitted"
              "channel": "EU KEV-new submission",
              "username": "${{ github.triggering_actor }}"
            }
